config:
  prefix: '&f[&eMPTimeChecker&f]'
  amount top: 10
  amount worst: 10
  generate tops time: 2h
  messages:
    no permission: '&cNo permission'
    unknown command: '&cUnknown command. &fTry /%command% help'
    reloaded: '&aFiles reloaded!'
    cannot check console: '&cThe console has been here since the beginning!'
    not exist: '&cThat player does not exist or has not played before.'
    self check: '&fYou have been playing for &c%time% &fon this server'
    other check: '&c%player% &fhas played for &c%time% &fon this server'
    error checking session: '&cThe session time could not be checked.'
    self session check: '&fYou have been playing &c%time% &fon this server for this session.'
    other session check: '&c%player% &fhas been playing &c%time% &fon this server for their last session.'
    top list: '&6&lTOP %amounttop% players by playtime:'
    worst list: '&6&lWORST %amountworst% players by playtime:'
    top player: '&f%pos%) &f%player%: &c%time%&f.'
    # Message shown when trying to get a player for the top players but there aren't enough of them in the top.
    error while getting player: '&cThere''s been an error while getting the top player'
    recalculating tops: '&eRecalculating tops... &7Remember that tops are automatically recalculated every X amount of time you set in config.'
    and: 'and'
    week: 'week'
    weeks: 'weeks'
    day: 'day'
    days: 'days'
    hour: 'hour'
    hours: 'hours'
    minute: 'minute'
    minutes: 'minutes'
    second: 'second'
    seconds: 'seconds'