config:
  prefix: '&f[&eMPTimeChecker&f]'
  messages:
    no permission: '&cNo permission'
    unknown command: '&cUnknown command. &fTry /%command% help'
    reloaded: '&aFiles reloaded!'
    cannot check console: '&cThe console has been here since the beginning!'
    not exist: '&cThat player does not exist or has not played before.'
    self check: '&fYou have been playing for &c%time% &fon this server'
    other check: '&c%player% &fhas played for &c%time% &fon this server'
    error checking session: '&cThe session time could not be checked.'
    self session check: '&fYou have been playing &c%time% &fon this server for this session.'
    other session check: '&c%player% &fhas been playing &c%time% &fon this server for their last session.'
    calculating: '&aCalculating...'
    top 10: '&6&lTOP 10 players by playtime:'
    top player: '%pos%) &f%player%: &c%time%&f.'
    and: 'and'
    week: 'week'
    weeks: 'weeks'
    day: 'day'
    days: 'days'
    hour: 'hour'
    hours: 'hours'
    minute: 'minute'
    minutes: 'minutes'
    second: 'second'
    seconds: 'seconds'